plugins {
    id "java"
}

group = "org.example"
version = "1.0.0"

repositories {
    mavenCentral()
}

List<String> platformList = [
    "natives-linux",
    "natives-linux-arm32",
    "natives-linux-arm64",
    "natives-macos",
    "natives-macos-arm64",
    "natives-windows",
    "natives-windows-x86",
    "natives-windows-arm64",
]

String lwjglVersion = rootProject.ext.lwjglVersion
String imguiVersion = "1.90.0"

dependencies {

    implementation "org.lwjgl:lwjgl:${lwjglVersion}"
    implementation "org.lwjgl:lwjgl-opengl:${lwjglVersion}"
    implementation "org.lwjgl:lwjgl-openal:${lwjglVersion}"
    implementation "org.lwjgl:lwjgl-glfw:${lwjglVersion}"
    implementation "org.lwjgl:lwjgl-vma:${lwjglVersion}"

    for (String platform : platformList) {

        runtimeOnly "org.lwjgl:lwjgl:${lwjglVersion}:${platform}"
        runtimeOnly "org.lwjgl:lwjgl-opengl:${lwjglVersion}:${platform}"
        runtimeOnly "org.lwjgl:lwjgl-openal:${lwjglVersion}:${platform}"
        runtimeOnly "org.lwjgl:lwjgl-glfw:${lwjglVersion}:${platform}"
        runtimeOnly "org.lwjgl:lwjgl-vma:${lwjglVersion}:${platform}"

        continue
    }

    implementation "org.joml:joml:1.9.17"
    implementation "io.github.spair:imgui-java-binding:${imguiVersion}"
    implementation "io.github.spair:imgui-java-lwjgl3:${imguiVersion}"
    implementation "io.github.spair:imgui-java-natives-windows:${imguiVersion}"

    implementation project(":go.graphics")
    implementation project(":go.graphics.swing")
    implementation project(":jsettlers.logic")
    implementation project(":jsettlers.network")
    implementation project(":jsettlers.common")
    implementation project(":jsettlers.graphics")
    implementation project(":jsettlers.main.swing")

    testImplementation platform("org.junit:junit-bom:5.10.0")
    testImplementation "org.junit.jupiter:junit-jupiter"
    testRuntimeOnly "org.junit.platform:junit-platform-launcher"
}

test {
    useJUnitPlatform()
}