plugins {
    id "java"
}

import jsettlers.shaders.compile.ShaderCompilationTask

java {
    sourceCompatibility = JavaVersion.VERSION_21
    targetCompatibility = JavaVersion.VERSION_21
}

String[] platformList = [
    "natives-linux",
    "natives-linux-arm32",
    "natives-linux-arm64",
    "natives-macos",
    "natives-macos-arm64",
    "natives-windows",
    "natives-windows-x86",
    "natives-windows-arm64",
]

dependencies {

	implementation project(':go.graphics')

	String lwjglVersion = rootProject.ext.lwjglVersion

    implementation "org.lwjgl:lwjgl:${lwjglVersion}"
    implementation "org.lwjgl:lwjgl-opengl:${lwjglVersion}"
    implementation "org.lwjgl:lwjgl-openal:${lwjglVersion}"
    implementation "org.lwjgl:lwjgl-glfw:${lwjglVersion}"
    implementation "org.lwjgl:lwjgl-vma:${lwjglVersion}"

    for (String platform : platformList) {
        runtimeOnly "org.lwjgl:lwjgl:${lwjglVersion}:${platform}"
        runtimeOnly "org.lwjgl:lwjgl-opengl:${lwjglVersion}:${platform}"
        runtimeOnly "org.lwjgl:lwjgl-openal:${lwjglVersion}:${platform}"
        runtimeOnly "org.lwjgl:lwjgl-glfw:${lwjglVersion}:${platform}"
        runtimeOnly "org.lwjgl:lwjgl-vma:${lwjglVersion}:${platform}"
    }

	implementation "org.lwjgl:lwjgl-vulkan:${lwjglVersion}:natives-macos"
	implementation "org.lwjgl:lwjgl-vulkan:${lwjglVersion}"
	implementation "org.lwjgl:lwjgl-egl:${lwjglVersion}"
	implementation "org.lwjgl:lwjgl-jawt:${lwjglVersion}"

	implementation "org.joml:joml:1.9.17"
	implementation "org.lwjglx:lwjgl3-awt:0.1.8"

	// macos support
	implementation "org.jogamp.gluegen:gluegen-rt:2.3.2"
	implementation "org.jogamp.jogl:jogl-all:2.3.2"
	runtimeOnly "org.jogamp.gluegen:gluegen-rt:2.3.2:natives-macosx-universal"
	runtimeOnly "org.jogamp.jogl:jogl-all:2.3.2:natives-macosx-universal"
}

String shaderDefinitionDir = 'src/main/glsl/'
String shaderJavaOutputDir = 'src/generated/java'
String shaderResOutputDir = 'src/generated/resources'

sourceSets {
	main.java.srcDirs += [shaderJavaOutputDir]
	main.resources.srcDirs += [shaderResOutputDir]
}

clean {
	delete file(shaderJavaOutputDir)
	delete file(shaderResOutputDir)
}

tasks.register("compileShaders", ShaderCompilationTask) {
    inputDirectory = file(shaderDefinitionDir).toPath()
    generatedSourcesDirectory = file(shaderJavaOutputDir).toPath()
    generatedResourcesDirectory = file(shaderResOutputDir).toPath()
}

compileJava {
	dependsOn compileShaders
}

copyMainResources {
	dependsOn compileShaders
}